apiVersion: v1
kind: Deployment
metadata:
  name: pdt-profiling-deployment
spec:
  selector:
    matchLabels:
      app: profiling-deployment
  template:
    metadata:
      labels:
        app: profiling-deployment
    spec:
      containers:
        - name: profiling-deployment
          image: eatonwu/pdt-profiling-deployment